- ros_topic_name: "/camera1/image/image"
  gz_topic_name: "/camera1/image/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera1/image/camera_info"
  gz_topic_name: "/camera1/image/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/lidar/cloud/points"
  gz_topic_name: "/lidar/cloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


- ros_topic_name: "camera1/image/depth_image"
  gz_topic_name: "camera1/image/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  frame_id: camera_link
  direction: GZ_TO_ROS